INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (1,'250',1,'Hospital','Baylor University Medical Center');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (2,'100',1,'Hospital','Charlton Methodist Hospital');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (3,'75',1,'Hospital','Children\'s Medical Center Dallas');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (4,'100',1,'Hospital','Doctors Hospital of Dallas');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (5,'175',1,'Hospital','Forest Park Medical Center - Dallas');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (6,'150',2,'Hospital','Medical City Dallas Hospital');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (7,'90',2,'Hospital','Methodist Medical Center');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (8,'80',2,'Hospital','Parkland Memorial Hospital');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (9,'120',3,'Hospital','Presbyterian Hospital');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (10,'160',3,'Hospital','Pine Creek Medical Center');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (11,'210',3,'Hospital','Texas Scottish Rite Hospital for Children');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (12,'225',3,'Hospital','St. Paul University Hospital');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (13,'60',3,'Hospital','University General Hospital');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (14,'200',3,'Hospital','Zale Lipshy University Hospital');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (15,'50',1,'Rehab Center','The Sanctuary');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (16,'60',1,'Rehab Center','Cirque Lodge');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (17,'70',1,'Rehab Center','Cottonwood de Tucson');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (18,'80',2,'Rehab Center','Caron Foundation');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (19,'100',2,'Rehab Center','Crossroads Center');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (20,'40',3,'Rehab Center','The Priory');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (21,'50',3,'Rehab Center','The Meadows Clinic');
INSERT INTO `health_infra` (`health_infra_id`,`health_infra_capacity`,`location_id`,`health_infra_type`,`health_infra_name`) VALUES (22,'75',3,'Rehab Center','Passages');