application: ******
version: 1
runtime: php55
api_version: 1
instance_class: F2
automatic_scaling:
  min_idle_instances: 5
  max_idle_instances: automatic 
  min_pending_latency: 30ms 
  max_pending_latency: automatic

handlers:
- url: /homescreen.php
  script: homescreen.php

- url: /register.php
  script: register.php

- url: /login.php
  script: login.php

- url: /upload.php
  script: upload.php

- url: /upload_handler.php
  script: upload_handler.php



